server:
  forward-headers-strategy: native
  port: 8080
#spring:
#  config:
#    import: optional:secrets.yml
#  datasource:
#    url: ${DATABASE_URL_DEV1}
#    username: ${DATABASE_USER1}
#    password: ${DATABASE_PASSWORD1}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
logging:
  level:
    org:
      #      root: TRACE
      springframework:
        messaging: DEBUG
        web: DEBUG
#        messaging:
#          support:
#          simp: DEBUG
#        security: TRACE
#      hibernate:
#        sql: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder:
#                TRACE